name: test
on: [push, pull_request]
jobs:
 build:
  runs-on: [ubuntu-latest]
  steps:
    - uses: actions/checkout@v4
    - name: Install cmake
      run: sudo apt install -y cmake build-essential
    - name: Build
      run:
        mkdir build
        cd build
        cmake ..
        make
